### ISSUE TITLE
User accounts

### ISSUE THREAD

**Issue by Davidster** [Davidster/SOEN341Project#1]
As a student or teacher's assistant, I want to be able to log into the website with my personal account.

**Comment by Megatron4537** [comment]
I created a Student and TA entities in MySQL that will hold records of all students and all TAs, respectively, and their personal information. I will work on the back-end of the registration page to automatically insert new students or TAs in the database. A php condition check will enable TAs to have more privileges over students.

**Comment by MikelShifrin** [comment]
I added basic content, structure and style to the website prior to login and created basic forms using HTML and CSS.

**Comment by Megatron4537** [comment]
The register page's back-end is now up and it will effectively add a student tuple (with id, name, email and password) to the Student records in MySQL.
