### ISSUE TITLE
Online participation

### ISSUE THREAD

**Issue by williamkingbede** [Davidster/SOEN341Project#11]
As a teacher assistant, I want to be able to see which team members are online while I am communicating with a group through the chat so that I can keep track of the members that are participating.

**Comment by TheAlexRobert** [comment]
How should we monitor online participation? The TA could check for himself, or we could implement a system that calculates how much time users spent of the site, or how much activity they have been doing.

**Comment by Megatron4537** [comment]
I say go for measure of a user's activity i.e. a group message is +0.5 pts, document upload is +5 pts, active 3 days in arow is awarded +5, 7 days in a row +15.
