### ISSUE TITLE
Group communication

### ISSUE THREAD

**Issue by Megatron4537** [Davidster/SOEN341Project#13]
As a student, I want to be able to communicate with my team so that we can share ideas and build our project.

**Comment by TheAlexRobert** [comment]
I am interested in doing this issue. Basically making a group chat (similar to Slack) for every member of the team?

**Comment by Megatron4537** [comment]
@TheAlexRobert  yes! I will help you on this with database management

**Comment by Megatron4537** [comment]
In MySQL, I created a relationship between a student and his project team that will contain the message he wishs to send and a time stamp to effectively sort messages in the chat.

**Comment by MikelShifrin** [comment]
I will add and modify an open source chat system implemented in PHP and MySQL and modify it accordingly to fit the team's needs
