### ISSUE TITLE
Student profile

### ISSUE THREAD

**Issue by Megatron4537** [Davidster/SOEN341Project#20]
As a student, I want to have a profile page where I can select for which project of mine I wish to work on.

**Comment by TheAlexRobert** [comment]
Can anyone check this page or only the account user?

**Comment by Megatron4537** [comment]
@TheAlexRobert  Only the account user

**Comment by SaiShan** [comment]
If everyone agrees, i can work on this issue using html css javascript php.

**Comment by kkepe** [comment]
Also, I can work on this issue with SaiShan by using html css javascript php
