### ISSUE TITLE
Uploading Files

### ISSUE THREAD

**Issue by kkepe** [Davidster/SOEN341Project#7]
As a teacher assistant, I want to be able to upload or remove course related
materials in order to provide tasks to students.

**Comment by Davidster** [comment]
The act of downloading course related materials is covered by issue #6 , so I would prefer to remove "or download"

Also, instead of "them", how about "the students"?

**Comment by kkepe** [comment]
Will change it, as soon as I get back home

**Comment by kkepe** [comment]
I am going to work on this User Story by adding file upload button and drag option by using div and input html tag with js and css. For removing, will use HTML 5's property called readonly FileList by using javascript to be able to remove desired file one at a time.

**Comment by MikelShifrin** [comment]
I am going to create the ability to upload a file using PHP and MySQL
