### ISSUE TITLE
Group contribution

### ISSUE THREAD

**Issue by Megatron4537** [Davidster/SOEN341Project#8]
As a teaching assistant, I want to be able to follow a specific team's project progess and track the 
contribution of each team members in order to have a fair grading.

**Comment by Davidster** [comment]
Looks good, but I'm not sure if we can get this done in the first sprint. I've added a simpler story #12  which is similar to this idea. 

Let me know what you think.

**Comment by Megatron4537** [comment]
Yeah you are right my friend
